/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as PedidoConfirmadoRouteImport } from './routes/pedido-confirmado'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CarrinhoRouteImport } from './routes/carrinho'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ProdutoIdRouteImport } from './routes/produto.$id'

const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidoConfirmadoRoute = PedidoConfirmadoRouteImport.update({
  id: '/pedido-confirmado',
  path: '/pedido-confirmado',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrinhoRoute = CarrinhoRouteImport.update({
  id: '/carrinho',
  path: '/carrinho',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoIdRoute = ProdutoIdRouteImport.update({
  id: '/produto/$id',
  path: '/produto/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/carrinho': typeof CarrinhoRoute
  '/checkout': typeof CheckoutRoute
  '/pedido-confirmado': typeof PedidoConfirmadoRoute
  '/produtos': typeof ProdutosRoute
  '/produto/$id': typeof ProdutoIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/carrinho': typeof CarrinhoRoute
  '/checkout': typeof CheckoutRoute
  '/pedido-confirmado': typeof PedidoConfirmadoRoute
  '/produtos': typeof ProdutosRoute
  '/produto/$id': typeof ProdutoIdRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/carrinho': typeof CarrinhoRoute
  '/checkout': typeof CheckoutRoute
  '/pedido-confirmado': typeof PedidoConfirmadoRoute
  '/produtos': typeof ProdutosRoute
  '/produto/$id': typeof ProdutoIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/carrinho'
    | '/checkout'
    | '/pedido-confirmado'
    | '/produtos'
    | '/produto/$id'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/carrinho'
    | '/checkout'
    | '/pedido-confirmado'
    | '/produtos'
    | '/produto/$id'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/carrinho'
    | '/checkout'
    | '/pedido-confirmado'
    | '/produtos'
    | '/produto/$id'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CarrinhoRoute: typeof CarrinhoRoute
  CheckoutRoute: typeof CheckoutRoute
  PedidoConfirmadoRoute: typeof PedidoConfirmadoRoute
  ProdutosRoute: typeof ProdutosRoute
  ProdutoIdRoute: typeof ProdutoIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedido-confirmado': {
      id: '/pedido-confirmado'
      path: '/pedido-confirmado'
      fullPath: '/pedido-confirmado'
      preLoaderRoute: typeof PedidoConfirmadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrinho': {
      id: '/carrinho'
      path: '/carrinho'
      fullPath: '/carrinho'
      preLoaderRoute: typeof CarrinhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto/$id': {
      id: '/produto/$id'
      path: '/produto/$id'
      fullPath: '/produto/$id'
      preLoaderRoute: typeof ProdutoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CarrinhoRoute: CarrinhoRoute,
  CheckoutRoute: CheckoutRoute,
  PedidoConfirmadoRoute: PedidoConfirmadoRoute,
  ProdutosRoute: ProdutosRoute,
  ProdutoIdRoute: ProdutoIdRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
